// utils/departmentList.ts

export const departmentList = {
  ENGINEERING: [
    "Mechanical Engineering (ME)",
    "Civil Engineering (CE)",
    "Electrical and Electronics Engineering (EEE)",
    "Computer Science and Engineering (CSE)",
    "Electronics and Communication Engineering (ECE)",
    "Information Technology (IT)",
    "Automobile Engineering",
    "Aerospace Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Agricultural Engineering",
    "Industrial Engineering",
    "Environmental Engineering",
    "Marine Engineering",
    "Artificial Intelligence and Data Science (AI & DS)",
    "Cyber Security and Forensics",
    "Robotics and Automation",
    "Internet of Things (IoT)",
    "Mechatronics Engineering",
    "Renewable Energy Engineering",
  ],
  ARTS: [
    "Tamil Literature",
    "English Literature",
    "History",
    "Economics",
    "Political Science",
    "Sociology",
    "Public Administration",
    "Philosophy",
    "Psychology",
    "Geography",
    "Social Work",
    "Journalism and Mass Communication",
    "Human Resource Management (HRM)",
    "Fine Arts (Painting, Sculpture, etc.)",
    "Visual Communication (VisCom)",
    "Performing Arts (Drama, Dance, etc.)",
    "Archaeology",
    "Tourism and Travel Management",
    "Library Science",
    "Women's Studies",
  ],
  MEDICAL: [
    "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
    "BDS (Bachelor of Dental Surgery)",
    "BAMS (Bachelor of Ayurvedic Medicine and Surgery)",
    "BHMS (Bachelor of Homeopathic Medicine and Surgery)",
    "BSMS (Bachelor of Siddha Medicine and Surgery)",
    "BUMS (Bachelor of Unani Medicine and Surgery)",
    "BPT (Bachelor of Physiotherapy)",
    "B.Sc. Nursing",
    "Pharmacy (B.Pharm / D.Pharm / Pharm.D)",
    "Occupational Therapy (BOT)",
    "BASLP (Bachelor of Audiology and Speech-Language Pathology)",
    "Radiology and Imaging Technology",
    "Medical Laboratory Technology (MLT)",
    "Anaesthesia Technology",
    "Optometry",
    "Cardiac Perfusion Technology",
    "Dialysis Technology",
    "Emergency and Trauma Care Technology",
    "Neuro Science Technology",
    "Clinical Nutrition and Dietetics",
  ],
};
