// utils/departmentList.ts

export const departmentList : any = {
  BE: [
    "B.E Mechanical Engineering (ME)",
    "B.E Civil Engineering (CE)",
    "B.E Electrical and Electronics Engineering (EEE)",
    "B.E Computer Science and Engineering (CSE)",
    "B.E Electronics and Communication Engineering (ECE)",
    "B.E Information Technology (IT)",
    "B.E Automobile Engineering",
    "B.E Aerospace Engineering",
    "B.E Chemical Engineering",
    "B.E Biomedical Engineering",
    "B.E Agricultural Engineering",
    "B.E Industrial Engineering",
    "B.E Environmental Engineering",
    "B.E Marine Engineering",
    "B.E Artificial Intelligence and Data Science (AI & DS)",
    "B.E Cyber Security and Forensics",
    "B.E Robotics and Automation",
    "B.E Internet of Things (IoT)",
    "B.E Mechatronics Engineering",
    "B.E Renewable Energy Engineering",
  ],
  ME: [
    "M.E Mechanical Engineering (ME)",
    "M.E Civil Engineering (CE)",
    "M.E Electrical and Electronics Engineering (EEE)",
    "M.E Computer Science and Engineering (CSE)",
    "M.E Electronics and Communication Engineering (ECE)",
    "M.E Information Technology (IT)",
    "M.E Automobile Engineering",
    "M.E Aerospace Engineering",
    "M.E Chemical Engineering",
    "M.E Biomedical Engineering",
    "M.E Agricultural Engineering",
    "M.E Industrial Engineering",
    "M.E Environmental Engineering",
    "M.E Marine Engineering",
    "M.E Artificial Intelligence and Data Science (AI & DS)",
    "M.E Cyber Security and Forensics",
    "M.E Robotics and Automation",
    "M.E Internet of Things (IoT)",
    "M.E Mechatronics Engineering",
    "M.E Renewable Energy Engineering",
  ],
  BTECH: [
    "B.Tech Mechanical Engineering (ME)",
    "B.Tech Civil Engineering (CE)",
    "B.Tech Electrical and Electronics Engineering (EEE)",
    "B.Tech Computer Science and Engineering (CSE)",
    "B.Tech Electronics and Communication Engineering (ECE)",
    "B.Tech Information Technology (IT)",
    "B.Tech Automobile Engineering",
    "B.Tech Aerospace Engineering",
    "B.Tech Chemical Engineering",
    "B.Tech Biomedical Engineering",
    "B.Tech Agricultural Engineering",
    "B.Tech Industrial Engineering",
    "B.Tech Environmental Engineering",
    "B.Tech Marine Engineering",
    "B.Tech Artificial Intelligence and Data Science (AI & DS)",
    "B.Tech Cyber Security and Forensics",
    "B.Tech Robotics and Automation",
    "B.Tech Internet of Things (IoT)",
    "B.Tech Mechatronics Engineering",
    "B.Tech Renewable Energy Engineering",
  ],
  MTECH: [
    "M.Tech Mechanical Engineering (ME)",
    "M.Tech Civil Engineering (CE)",
    "M.Tech Electrical and Electronics Engineering (EEE)",
    "M.Tech Computer Science and Engineering (CSE)",
    "M.Tech Electronics and Communication Engineering (ECE)",
    "M.Tech Information Technology (IT)",
    "M.Tech Automobile Engineering",
    "M.Tech Aerospace Engineering",
    "M.Tech Chemical Engineering",
    "M.Tech Biomedical Engineering",
    "M.Tech Agricultural Engineering",
    "M.Tech Industrial Engineering",
    "M.Tech Environmental Engineering",
    "M.Tech Marine Engineering",
    "M.Tech Artificial Intelligence and Data Science (AI & DS)",
    "M.Tech Cyber Security and Forensics",
    "M.Tech Robotics and Automation",
    "M.Tech Internet of Things (IoT)",
    "M.Tech Mechatronics Engineering",
    "M.Tech Renewable Energy Engineering",
  ],
  BSC: [
    "B.Sc Tamil Literature",
    "B.Sc English Literature",
    "B.Sc History",
    "B.Sc Economics",
    "B.Sc Political Science",
    "B.Sc Sociology",
    "B.Sc Public Administration",
    "B.Sc Philosophy",
    "B.Sc Psychology",
    "B.Sc Geography",
    "B.Sc Social Work",
    "B.Sc Journalism and Mass Communication",
    "B.Sc Human Resource Management (HRM)",
    "B.Sc Fine Arts (Painting, Sculpture, etc.)",
    "B.Sc Visual Communication (VisCom)",
    "B.Sc Performing Arts (Drama, Dance, etc.)",
    "B.Sc Archaeology",
    "B.Sc Tourism and Travel Management",
    "B.Sc Library Science",
    "B.Sc Women's Studies",
  ],
  MSC: [
    "M.Sc Tamil Literature",
    "M.Sc English Literature",
    "M.Sc History",
    "M.Sc Economics",
    "M.Sc Political Science",
    "M.Sc Sociology",
    "M.Sc Public Administration",
    "M.Sc Philosophy",
    "M.Sc Psychology",
    "M.Sc Geography",
    "M.Sc Social Work",
    "M.Sc Journalism and Mass Communication",
    "M.Sc Human Resource Management (HRM)",
    "M.Sc Fine Arts (Painting, Sculpture, etc.)",
    "M.Sc Visual Communication (VisCom)",
    "M.Sc Performing Arts (Drama, Dance, etc.)",
    "M.Sc Archaeology",
    "M.Sc Tourism and Travel Management",
    "M.Sc Library Science",
    "M.Sc Women's Studies",
  ],
};
